/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2016-12-20 15:30:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.admin.addStudent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(12);
    _jspx_dependants.put("jar:file:/Users/yutsukimiyashita/Documents/workspace/gakugeiJob/src/main/webapp/WEB-INF/lib/struts-1.2.9.jar!/META-INF/tlds/struts-bean.tld", Long.valueOf(1141885850000L));
    _jspx_dependants.put("jar:file:/Users/yutsukimiyashita/Documents/workspace/gakugeiJob/src/main/webapp/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/Users/yutsukimiyashita/Documents/workspace/gakugeiJob/src/main/webapp/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/struts-1.2.9.jar", Long.valueOf(1482244816000L));
    _jspx_dependants.put("jar:file:/Users/yutsukimiyashita/Documents/workspace/gakugeiJob/src/main/webapp/WEB-INF/lib/struts-1.2.9.jar!/META-INF/tlds/struts-tiles-1.1.tld", Long.valueOf(1141885850000L));
    _jspx_dependants.put("/WEB-INF/lib/sa-struts-1.0.4-sp9.jar", Long.valueOf(1482244816000L));
    _jspx_dependants.put("jar:file:/Users/yutsukimiyashita/Documents/workspace/gakugeiJob/src/main/webapp/WEB-INF/lib/sa-struts-1.0.4-sp9.jar!/META-INF/f.tld", Long.valueOf(1313227424000L));
    _jspx_dependants.put("jar:file:/Users/yutsukimiyashita/Documents/workspace/gakugeiJob/src/main/webapp/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/Users/yutsukimiyashita/Documents/workspace/gakugeiJob/src/main/webapp/WEB-INF/lib/struts-1.2.9.jar!/META-INF/tlds/struts-html.tld", Long.valueOf(1141885850000L));
    _jspx_dependants.put("jar:file:/Users/yutsukimiyashita/Documents/workspace/gakugeiJob/src/main/webapp/WEB-INF/lib/sa-struts-1.0.4-sp9.jar!/META-INF/s.tld", Long.valueOf(1313227424000L));
    _jspx_dependants.put("/WEB-INF/view/common/common.jsp", Long.valueOf(1482243909000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1482244816000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fflush;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005ftype_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fflush = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005ftype_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fflush.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005ftype_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  \n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_tiles_005finsert_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsert_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f0 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fflush.get(org.apache.struts.taglib.tiles.InsertTag.class);
    try {
      _jspx_th_tiles_005finsert_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsert_005f0.setParent(null);
      // /WEB-INF/view/admin/addStudent/index.jsp(1,1) name = template type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsert_005f0.setTemplate("/WEB-INF/view/common/admin/layout.jsp");
      // /WEB-INF/view/admin/addStudent/index.jsp(1,1) name = flush type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsert_005f0.setFlush(true);
      int _jspx_eval_tiles_005finsert_005f0 = _jspx_th_tiles_005finsert_005f0.doStartTag();
      if (_jspx_eval_tiles_005finsert_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write('	');
          if (_jspx_meth_tiles_005fput_005f0(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          if (_jspx_meth_tiles_005fput_005f1(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          int evalDoAfterBody = _jspx_th_tiles_005finsert_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tiles_005finsert_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fflush.reuse(_jspx_th_tiles_005finsert_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f0 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fvalue_005fname_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    try {
      _jspx_th_tiles_005fput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005fput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
      // /WEB-INF/view/admin/addStudent/index.jsp(2,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fput_005f0.setName("title");
      // /WEB-INF/view/admin/addStudent/index.jsp(2,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fput_005f0.setValue("Home");
      int _jspx_eval_tiles_005fput_005f0 = _jspx_th_tiles_005fput_005f0.doStartTag();
      if (_jspx_th_tiles_005fput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_tiles_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f1 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005ftype_005fname.get(org.apache.struts.taglib.tiles.PutTag.class);
    try {
      _jspx_th_tiles_005fput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005fput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
      // /WEB-INF/view/admin/addStudent/index.jsp(3,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fput_005f1.setName("content");
      // /WEB-INF/view/admin/addStudent/index.jsp(3,1) name = type type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fput_005f1.setType("string");
      int _jspx_eval_tiles_005fput_005f1 = _jspx_th_tiles_005fput_005f1.doStartTag();
      if (_jspx_eval_tiles_005fput_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tiles_005fput_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_tiles_005fput_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_tiles_005fput_005f1.doInitBody();
        }
        do {
          out.write("\n");
          out.write("\t\t<div class=\"jumbotron text-center\" style=\"background-color:#FFE;coror:#000\">\t\n");
          out.write(" \t \t\t<h1 class=\"text-center\">GakugeiJob!</h1>\n");
          out.write(" \t \t</div>\n");
          out.write(" \t \t<br>\n");
          out.write(" \t \t<h2 class=\"text-center\">学生情報登録</h2>\n");
          out.write("\t\t\n");
          out.write("\t\t<div class=\"container\">\n");
          out.write(" \t \t<h1 class=\"page-header\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>入力項目に適していないとき、またユーザーIDが既に使われている場合エラーになります。</small></h1><br>\t\n");
          out.write("        \t<form name=\"addStudentActionForm\" class=\"form-horizontal\" action=\"/gakugeiJob/admin/addStudent/\" method=\"POST\">\n");
          out.write("\t\t\t\t<div class=\"form-group\">\n");
          out.write("\t\t\t\t<label class=\"col-sm-2 control-label\">ユーザーID:</label>\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-3\"><input type=\"text\" class=\"form-control\" name=\"userId\" maxlength=\"12\" required autofocus></div>\n");
          out.write("\t\t\t\t<div class=\"col-sm-7\"><p class=\"help-block\">12文字以内で入力してください。(学籍番号推奨)</p></div>\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t</div>\n");
          out.write("\t\t\t\t<div class=\"form-group\">\n");
          out.write("\t\t\t\t<label class=\"col-sm-2 control-label\">ユーザーパスワード:</label>\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-3\"><input type=\"text\" class=\"form-control\" name=\"userPass\" maxlength=\"12\" required></div>\n");
          out.write("\t\t\t\t<div class=\"col-sm-7\"><p class=\"help-block\">12文字以内で入力してください。(\"root推奨\")</p></div>\n");
          out.write("\t\t\t\t</div>     \t\n");
          out.write("\n");
          out.write("\t\t\t\t<div class=\"col-sm-offset-2 col-sm-10 text-right\"><br>\n");
          out.write("\t     \t    \t<button class=\"btn btn-lg btn-default\" type=\"submit\" name=\"add\" value=\"Add\">新規登録</button>\n");
          out.write("\t     \t    </div>\n");
          out.write("      \t\t</form>\n");
          out.write("      \t</div> <!-- container -->\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_tiles_005fput_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tiles_005fput_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tiles_005fput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005ftype_005fname.reuse(_jspx_th_tiles_005fput_005f1);
    }
    return false;
  }
}
